# GNUmake file of AngraSimulation
# 
# Authors: P.Chimenti, R.Lima
#
# 30-4-2008: v0.01
# 

name :=  AngraSimulations
G4TARGET := $(name)
G4EXLIB := true

.PHONY: all
all: lib bin

include $(G4INSTALL)/config/binmake.gmk
